Name:           ros-indigo-flask-ext-catkin
Version:        0.1.0
Release:        2%{?dist}
Summary:        ROS flask_ext_catkin package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/asmodehn/flask-ext-catkin
Source0:        %{name}-%{version}.tar.gz

Requires:       python-alembic
Requires:       python-flask
Requires:       python-itsdangerous
Requires:       python-passlib
BuildRequires:  python-alembic
BuildRequires:  python-catkin_pkg
BuildRequires:  python-flask
BuildRequires:  python-itsdangerous
BuildRequires:  python-passlib
BuildRequires:  ros-indigo-catkin

%description
Catkinized version of flask extensions python packages

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Jun 11 2015 AlexV <asmodehn@gmail.com> - 0.1.0-2
- Autogenerated by Bloom

* Wed Jun 10 2015 AlexV <asmodehn@gmail.com> - 0.1.0-1
- Autogenerated by Bloom

* Mon Jun 08 2015 AlexV <asmodehn@gmail.com> - 0.1.0-0
- Autogenerated by Bloom

